### ISSUE TITLE
Leichte Installation aber konte nicht hacken

### ISSUE THREAD

**Issue by Nogay68** [mishakorzik/Gmail-Hack#11]
![Screenshot_20230222-234341_Termux](https://user-images.githubusercontent.com/126032392/220778110-641c3807-aa18-4f07-bd0b-96a460303655.jpg)

**Comment by Nogay68** [comment]
Eine bessere Passwort liste mit update wäre gut, ich weiß leider nicht wie man das macht. hat jemand ein besseren idee.

**Comment by mishakorzik** [comment]
this is not a Gmail-Hack problem, maybe you have some complications with the smtp module
