### ISSUE TITLE
Gmail hack

### ISSUE THREAD

**Issue by MsaRaju** [mishakorzik/Gmail-Hack#2]
Installing for termux

termux-setup-storage

apt full-upgrade

apt install git

git clone https://github.com/mishakorzik/Gmail-Hack

cd Gmail-Hack

bash install.sh

Installing for linux

apt upgrade

apt install git

git clone https://github.com/mishakorzik/Gmail-Hack

cd Gmail-Hack

bash install.sh

Start Gmail-Hack

cd && cd Gmail-Hack && python3 Mail-Hack.py

If it does not work then the command:

python3 Mail-Hack.py

**Comment by MsaRaju** [comment]
Installing for termux

termux-setup-storage

apt full-upgrade

apt install git

git clone https://github.com/mishakorzik/Gmail-Hack

cd Gmail-Hack

bash install.sh

Installing for linux

apt upgrade

apt install git

git clone https://github.com/mishakorzik/Gmail-Hack

cd Gmail-Hack

bash install.sh

Start Gmail-Hack

cd && cd Gmail-Hack && python3 Mail-Hack.py

If it does not work then the command:

python3 Mail-Hack.py

**Comment by mishakorzik** [comment]
You operating system?

**Comment by Dumindudananjaya** [comment]
Ok
