### ISSUE TITLE
Termux not responding

### ISSUE THREAD

**Issue by Robertcheq21** [mishakorzik/Gmail-Hack#9]
$ termux-setup-storage                                                                              Directory '~/storage' is going to be wiped. No storage contents will be touched.                    
Do you want to continue ? (y/n) y                 $ apt full-upgrade
Reading package lists... Done                     Building dependency tree... Done                  Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
$ apt install git                                 Reading package lists... Done
Building dependency tree... Done                  E: Unable to locate package git                  my termux ain't responding

**Comment by mishakorzik** [comment]
this is not a gmail hack problem
